[lib]
proc-macro = true

[package]
name = "gc_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.93"

[dev-dependencies]
gc = { path = "../gc" }
trybuild = "1.0.101"
